{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "postit.serviceAccountName" . }}
  labels:
{{ include "postit.labels" . | nindent 4 }}
{{- end -}}
